added debug lines to docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -13,6 +13,8 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Debug .dockerignore
+      run: cat .dockerignore || echo ".dockerignore not found"
     - uses: actions/checkout@v4
     - name: List files for debugging
       run: ls -al
